branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"

sudo: false

compiler: clang

env:
  global:
  - JOBS: '8'
  - secure: "J5YHZej1DQBvgFHrn/H4oPODJHWZhJkdwCz91YknXmSkzKwsof4f5VHRz59KCYW0ndrnxA9FEPCpQW/76qox00WbmI5Knpd69uk5SRTKppb1J1JyFoaz7//530QqHwlRrmGnSvMVjOMV0Fd5CPkJK8lKYtu+2WwuqrM243YAka7jTDpnxUPet5PYqlKp0LoAWwAs3ukPepI2e/xKEd1AsMuaCtBvW5Ml8v43ggVPKmq6lT7cEf1qz70iGl8W0amgu0q8RX6ZvqRrlSALy01cim4lgUuE6qjgISz9cArVVIMMrpNBW+9uWlrEBze0wycS1yUwd0pJoYoXbOtGx4eayAcYXDm5ODBlXYurqd1RzPA1EylTyQQYuKhs5aSrjydYlMa970aLS0o5AFSYo+Oxi9RicawQ5eJVz/NY8xkJ/N8s8ToQXve+qaLZJUhi93BryOp77iFvphuwnMJIa9KfytwW87CYp109IdzvsdarlX13TJphJyh1GwIbgq9DXDnCnG4y5evtH9sUTC4uvFJPAIH3PhewtHafaZ1kl21Q7wSzubjpOJPsZKjsLB7/waBngm9njaoBZtbcLG9cpWLkok0m3b6KKIwP/iLSuZhRpJOkXHNA7kFxAWpdeAFsl7/6T5qnG1BbBBf9wmWvkyyxMflhea1tIQIcFEHdeN6EO/A="
  - secure: "fzmACKHyXYDtMqrxYxxf7QyK7o9V06BkHlg402cPX3SNkMU96frYaK2JEHuO5DiOk0+U1KRbaOK4HIj0kk+BzqcfZHsCTLInSw3sr2BY6jaFXA5HHSks/sQ3LTTnblHPrPg4M6C7d+DEehGqtocN0MneErEPwNkCkKHqZCVyim9OXkRFp6WHFTaAPUmKGhqG8YWuiMpo1x9/fg2a4XD5Z0m+DXrVsftafCZ2+j2ZtChu2ppnQmw2a1V8HozhGvYn0o+2Dc65UHZLArModMhPFITBUBQ1/TRiuLpOWmwY7PuCvvz2ZHMeq1oPISJhaa+bjwOfL2pb9D5CXqwalZfbzBp/JJ1oWuwm3k0Rywzi7bX829gu71ezJyaPs9GTPsKEtSHJCtPmYObN9RdmAgNELDjAX29Oy8TLQtWkOcJ6cxShQa3yRsWp1YRPjX4JBoP/cbfNXFQbKiICG1G9Rdy062rnjXVYVu5D4W8PbmFIEpEvrxz1969eSy0XwY5AP3IQJKbjs6cVsdyi52fq1tl3bwyfMXK6luYhUm7cm9EiC2U7mKV6tmpesLRwG61rKPIAkWo6wfWJrMEtb5oXuFmt9hUF+DMuuWs9Ce432yDl6e0dG5uhExvT795dkwiftWt5Y8q9afWTeW8NpwEfiJN4T+tCHkTgFkDSC2X+PZo2zn0="

matrix:
  fast_finish: true
  include:
  - os: linux
    env: export NODE_VERSION="9.8" TARGET_ARCH="x64" RUNTIME="node"
  - os: linux
    env: export NODE_VERSION="8.10" TARGET_ARCH="x64" RUNTIME="node"
  - os: linux
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="node"
  - os: linux
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="electron" TARGET="1.6.6"
  - os: osx
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="node"
  - os: osx
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="electron" TARGET="1.6.6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - libssl-dev
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - lcov

install:
- source scripts/install.sh

script:
- if [ -z "$TARGET" ]; then npm test; fi

after_success:
- scripts/publish.sh
