branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"

sudo: false

compiler: clang

env:
  global:
  - JOBS: '8'
  - secure: xK36kZQzjgVoOU+N446kWMEUwI8jFs9zmMrpYckKZEPRpg8stAIxJ4UkRHHr1d6Cq1XUgmPqk0c9A/MFYE38C6clE3dv9envqwI9Vkzg/lfJ0ebKdHFA7AAwMjD36KxNSdMOPVBIMNFgs1tln3NCgQDtDq32RwyHD8/xldXTx07y7/m4t3lu7ee5kSsbfXjLVKkKVRfTn8gM+cliIumax8keiEzBYpTf4Wl43K7d5ceSibr2+XtkjofsUSvp9awiWxn+JReBjPnRv5k9CwavFk29hlgd+wk89DrHjg3nq5v3bSXJZRI3fStaSXlz7C4X/UVYKENwjMNEgUJ1dehJa+EGGb07u8wMKK0BQjCAwzzUx9LzdgL4wuw1ZT5Agak3dR1PJvOIIQLF5moo27TCMLJivjmqUtaiqNGOubYXvgjARlhQNwC7+tTlguRvS5WjzOIUKy4KOAjJddh+VhYHgYKSLfTJUrapG0MZ/uGF5Yp6wlJkyWviYgptDRBf2WK4pDqQCEvCf6KF9V1vpNtd60uQRniwnrSzal8vbYoBSWe6cmkQOVwEpgYZvmnxBo9ZPS0glSJceYxXWZ+FVXjTORam2Brrzw2L6J+GCxGJywkn6xffwsWmr0uBPnTvUpj2baNMMfNzPdcOKrHa2sGP9dCpt6FHPyF6Ga8f2a+ZDwg=
  - secure: Jn6Q+eDlMTouzsxyXYVP1c502SHSsF4QPke3287Su1vFppxT/rI78Q7L4dLsTLD16hOhoMUevGQpfprG4bGVIKA4IlHfnxbGnflmzQwX/F5eNbRSXXBeVItzl/Xw6E4puf56FD+U/557Y7/D1iPrbOlS+FazSv1WrTaMhnyJYHOLCDL28bNjMfJSUEiMsqU0YIISNZBP9FasYY1YSkBZ4GMJL20ReSbraWB1KOrJ7ZUhlCcLnL6LOdERjMXAxaUOSe5MG1Yo7mHi7etHodQATPlQw27E46T8Qkdbr9MyGDsv+9iRdcVNz7u886YkV//j320RI9YfKk3v5Iq2zBSDY4/YQEy/42LsBNl4b4rX/9kv3CdrTqhwak/wwJDw9nrKUPDZ7Zup91XlnSACPs31G1ZQFaRGJFxNLnHBsg9lrjfmCDYVsXYL/tlZ35EECSL2xVMwgx/s5WplWYo1ki+ea/8GLrlRq/wKxSQFhwGxRdsp323/hEGkd4hE7OBmlApBOVJZPQZlGNeBgHkiBYGBXHC/FBVfz0W8iAoFdh3e+jKyDC62u2Nj2qrCu4Yh8AglBOVwzti1pLD5jGFWAfnrYX7n4EUBJWSLv1Emr0TOJheaww3wt4dqYv3YY2vsHsPwn5nl9OZucjmNxpP1g4AYKdxxzUPsORKzkaAEXTmtKY0=

matrix:
  fast_finish: true
  include:
  - os: linux
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="node"
  - os: linux
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="electron" TARGET="1.6.6"
  - os: osx
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="node"
  - os: osx
    env: export NODE_VERSION="7.6" TARGET_ARCH="x64" RUNTIME="electron" TARGET="1.6.6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - libssl-dev
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - lcov

install:
- source scripts/install.sh

script:
- if [ -z "$TARGET" ]; then npm test; fi

after_success:
- scripts/publish.sh
